# ============================================
# Nixpacks Configuration for Railway
# ============================================
# Simplified configuration - let Railway auto-detect Node.js or Python per service
# Build and start commands are configured per service in Railway dashboard

[variables]
# Environment variables for the build process
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
