# Railway configuration for lipton-doc-pipeline (Python) service

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.python"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

# Environment variables
# These should be set in Railway UI under the service Variables tab
# REQUIRED:
# - DATABASE_URL=${{lipton-database.DATABASE_URL}}
# - PYTHON_ENV=production
# - PORT=8000
#
# The DATABASE_URL will be automatically populated from the lipton-database service
